### ISSUE TITLE
Implement pagination & search for users list

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow#266]
The users list (shown below) has two problems that we want to tackle: first, it does filtering on the client side, resulting in poor performance on mobile devices for large lists. Secondly, it is not consistent with the rest of the app, where the filtering happens on the backend.

![users](https://user-images.githubusercontent.com/762088/31614817-eec704b8-b287-11e7-865a-181877b9002d.png)

Also, we would like to get rid of Angular to cut off some complexity that we think is not needed. It can greatly simplify the app and make it easier for others to contribute to the project.

## Requirements

- [ ] Paginate the response in the backend, so that not all records are returned in one go. This is already done in offers. See image below:

![offers](https://user-images.githubusercontent.com/762088/31614995-6b352796-b288-11e7-81aa-b593854d0fdc.png)

- [ ] Change the search field to query Elasticsearch, rather than filtering on the client side. Again this is already done in `offers/dashboard`.

- [ ] Remove all the now unused Angular machinery. We might not be able to completely remove Angular as it might be used in some other corner of the app.

This clearly fits in two isolated PRs that would go together in the next release.

**Comment by vraravam** [comment]
@sauloperez - i'll take a stab at incorporating pagination.

**Comment by ankitbhardwaj78** [comment]
@sauloperez  i want to take work on it.

**Comment by sauloperez** [comment]
Sorry @knoopx is already working on it in https://github.com/coopdevs/timeoverflow/pull/272.

You can also pick up some issues in https://github.com/openfoodfoundation/openfoodnetwork/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3AHacktoberfest%20

**Comment by vraravam** [comment]
@sauloperez - im not able to get the `bundle` command to work - maybe the version of `active_admin` is incorrect?

**Comment by enricostano** [comment]
@vraravam I guess the `bundle` issue is solved by https://github.com/coopdevs/timeoverflow/pull/273

Thanks for contributing! 💪

**Comment by vraravam** [comment]
@enricostano - i still don't see #273 being merged into master - so, I'm still stuck.

**Comment by sauloperez** [comment]
@vraravam you can upgrade the gems to the exact same version of #273
